spring:
  data:
    redis:
      host: 192.168.227.128
      port: 6379
      password: 123321
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms
    #哨兵集群模式端口配置 三个哨兵节点
#    cluster:
#      nodes:
#        - 192.168.150.101:27001
#        - 192.168.150.101:27002
#        - 192.168.150.101:27003

    #分片集群模式端口配置 三主三从
    cluster:
      nodes:
        - 192.168.150.101:7001
        - 192.168.150.101:7002
        - 192.168.150.101:7003
        - 192.168.150.101:8001
        - 192.168.150.101:8002
        - 192.168.150.101:8003